// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // CLI only (migrate/studio/db) — the app itself connects via DATABASE_URL in src/lib/prisma.ts.
  // Migrations take a Postgres advisory lock, which is unreliable through the connection pooler
  // (pooled.db.prisma.io) and timed out a production build (P1002), so prefer the direct
  // connection (db.prisma.io) when it's set.
  datasource: {
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
